services:

  backend:
    build:
      context: ./backend/tutor
      dockerfile: Dockerfile

    ports:
      - "8001:8000"

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://postgres:hello2020@db:5432/tutor
      POSTGRES_DB: tutor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello2020
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    volumes:
      - ./backend/tutor:/app

  db:
    image: postgres:17

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello2020
      POSTGRES_DB: tutor

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend

    depends_on:
      - backend

    ports:
      - "80:80"
volumes:
  postgres_data: