# Generated by Django 6.1.1 on 2026-09-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_alter_subtopic_codes_alter_subtopic_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='img_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
