# Generated by Django 6.1.1 on 2026-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_subtopic_img_name_delete_codesnippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='img_name',
        ),
        migrations.AddField(
            model_name='topic',
            name='img_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
