# Generated by Django 6.1.1 on 2026-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_remove_subtopic_img_name_topic_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
